# Use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix M-a
unbind-key C-b
bind-key M-a send-prefix
set -g base-index 1

# vi is good
setw -g mode-keys vi

# Use Alt-vim keys without prefix key to switch panes
bind-key h select-pane -L
bind-key j select-pane -D 
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing.
bind -r M-h resize-pane -L 1
bind -r M-j resize-pane -D 1
bind -r M-k resize-pane -U 1
bind -r M-l resize-pane -R 1

# bind-key e run-shell "echo hello"
bind e send "echo hello" C-m
