# Gruvbox Dark palette
set -g @palette-bg0    "#282828"
set -g @palette-bg1    "#3c3836"
set -g @palette-bg2    "#504945"
set -g @palette-bg3    "#665c54"
set -g @palette-fg1    "#ebdbb2"
set -g @palette-fg2    "#d5c4a1"
set -g @palette-fg3    "#bdae93"
set -g @palette-accent "#fe8019"
set -g @palette-alert  "#fb4934"

set-option -g status-style "bg=#{@palette-bg1},fg=#{@palette-fg1}"
set-window-option -g window-status-activity-style bold,underscore
set-option -g pane-active-border-style "fg=#{@palette-fg3}"
set-option -g pane-border-style "fg=#{@palette-bg1}"
set-option -g message-style "bg=#{@palette-bg2},fg=#{@palette-fg1}"
set-option -g message-command-style "bg=#{@palette-bg2},fg=#{@palette-fg1}"
set-option -g display-panes-active-colour "#bdae93"
set-option -g display-panes-colour "#3c3836"

set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[fg=#{@palette-fg2},bg=#{@palette-bg3}] #S #{?pane_synchronized,#[fg=#{@palette-alert}] SYNC ,}#[fg=#{@palette-bg3},bg=#{@palette-bg1},nobold,noitalics,nounderscore]"
set-option -g status-right "#[fg=#{@palette-fg2},bg=#{@palette-bg1}] %H:%M %d-%b #[fg=#{@palette-fg2},bg=#{@palette-bg1}]#{?client_prefix,#[reverse] ⌨ #[noreverse],}#[fg=#{@palette-bg1},bg=#{@palette-fg2}] #h "
set-window-option -g window-status-current-format "#[fg=#{@palette-bg1},bg=#{@palette-accent}] [#I]#[fg=#{@palette-bg1},bg=#{@palette-accent},bold] #W#{?window_zoomed_flag, Z,} "
set-window-option -g window-status-format "#[fg=#{?window_bell_flag,#{@palette-bg0},#{@palette-fg1}},bg=#{?window_bell_flag,#{@palette-alert},#{@palette-bg2}}] [#I]#[fg=#{?window_bell_flag,#{@palette-bg0},#{@palette-fg1}},bg=#{?window_bell_flag,#{@palette-alert},#{@palette-bg2}}] #W "
